// New Lords — citygen.js — PCG city runtime (generatePCGTown, buildCity, walkers, pcg* helpers)
// Auto-split from new-lords-prototype.html (#65). THREE is the global from the classic r128 script.

import { ENT, S, mulberry32 } from './state.js';
import { root } from './render.js';

/* =====================================================================
   CLOSE LOD — a real town, generated by the PCG CITY GENERATOR (#64).

   This is a faithful port of the standalone `city-generator.html` runtime —
   itself a text-graph reimplementation of Epic's PCGPrimitives example
   `City_Circular_1km_2_arteries_NoAssetLibrary` (see docs/pcg/city_generator.md
   and docs/pcg/city_generator.graph.json). The pipeline is a 2-D area/spline
   dataflow, deterministic per settlement seed (cityRng -> mulberry32):

     outline -> arteries -> districts -> blocks -> lots -> buildings + dressing

   generatePCGTown(st) runs the whole pipeline in metres, then normalises every
   coordinate to the town's outline radius (~1.0) so buildCity() can project the
   result onto the sphere with its existing up/tan/bit basis + orient()/dirOf().
   The generated LOCAL STREET NETWORK (buildStreetGraph) replaces the old
   "corridors between recursively-split blocks" the cats used to walk — residents
   now follow an explicit street graph whose nodes sit in the road ring around
   every lot, so a waypoint is always on a street and never inside a building.

   Per-tier profiles (PCITY) scale radius / block size / district limit /
   buildable ratio / building height, and gate the heavy stages: megalopolis runs
   the full pipeline (2 arteries, district split, dense blocks); city is lighter
   (1 artery); village and camp have NO arteries and progressively fewer blocks —
   a camp is a minimal lot cluster. Game scale: 1 surface-unit maps a per-tier
   real radius Rm (m); the UE reference is a 1 km hex with 120x60 m blocks and a
   60 m max height (megalopolis), rescaled down the tiers.
   ===================================================================== */
const PCITY = {
  //             surface R  real-m  arteries  block WxL(m)  distSplit  distLimit(m^2)  road widths (m)          buildable  parkPct  parkArea(m^2)  maxH(m)  hExag  treeDens
  camp:        {radius:0.0085, Rm:66,  arteries:0, blockW:48,  blockL:36, distIter:0, distLimit:1e9,   roadArtery:0,  roadColl:0,  roadLocal:6,  buildable:0.72, parkPct:0.03, parkArea:1e9,  maxH:8,  heightExag:3.0, treeDens:0.0009},
  village:     {radius:0.0200, Rm:150, arteries:0, blockW:86,  blockL:58, distIter:0, distLimit:1e9,   roadArtery:0,  roadColl:0,  roadLocal:10, buildable:0.80, parkPct:0.13, parkArea:9000, maxH:15, heightExag:3.3, treeDens:0.0010},
  city:        {radius:0.0320, Rm:340, arteries:1, blockW:120, blockL:60, distIter:1, distLimit:30000, roadArtery:34, roadColl:24, roadLocal:16, buildable:0.88, parkPct:0.15, parkArea:7000, maxH:44, heightExag:4.0, treeDens:0.0011},
  megalopolis: {radius:0.0420, Rm:520, arteries:2, blockW:120, blockL:60, distIter:1, distLimit:32000, roadArtery:40, roadColl:26, roadLocal:19, buildable:0.92, parkPct:0.15, parkArea:8000, maxH:60, heightExag:4.4, treeDens:0.0011},
};
/* deterministic, region-local per settlement + world seed (unchanged from #17/#18). */
function cityRng(st){ return mulberry32((st.id*2654435761 ^ S.seed*40503)>>>0); }

/* ---- PCG polygon helpers (poly = [{x,y}...], metres, kept CCW) ---- */
function pcgArea2(p){let s=0;for(let i=0,n=p.length;i<n;i++){const a=p[i],b=p[(i+1)%n];s+=a.x*b.y-b.x*a.y;}return s/2;}
function pcgArea(p){return Math.abs(pcgArea2(p));}
function pcgCcw(p){return pcgArea2(p)<0?p.slice().reverse():p;}
function pcgCentroid(p){let x=0,y=0;for(const q of p){x+=q.x;y+=q.y;}return{x:x/p.length,y:y/p.length};}
function pcgBbox(p){let a=1e9,b=1e9,c=-1e9,d=-1e9;for(const q of p){a=Math.min(a,q.x);b=Math.min(b,q.y);c=Math.max(c,q.x);d=Math.max(d,q.y);}return{minx:a,miny:b,maxx:c,maxy:d};}
function pcgHash2(x,y){let h=Math.sin(x*127.1+y*311.7)*43758.5453;return h-Math.floor(h);}
function pcgVnoise(x,y){ // value noise in [0,1] — position-based, deterministic, draws no rng
  const xi=Math.floor(x),yi=Math.floor(y),xf=x-xi,yf=y-yi;
  const u=xf*xf*(3-2*xf),v=yf*yf*(3-2*yf);
  const a=pcgHash2(xi,yi),b=pcgHash2(xi+1,yi),c=pcgHash2(xi,yi+1),d=pcgHash2(xi+1,yi+1);
  return a*(1-u)*(1-v)+b*u*(1-v)+c*(1-u)*v+d*u*v;
}
// Sutherland-Hodgman: keep the half-plane left of directed line a->b
function pcgClipHalf(poly,a,b){
  const out=[];const n=poly.length;const side=p=>(b.x-a.x)*(p.y-a.y)-(b.y-a.y)*(p.x-a.x);
  for(let i=0;i<n;i++){
    const cur=poly[i],nxt=poly[(i+1)%n];const sc=side(cur),sn=side(nxt);
    if(sc>=0)out.push(cur);
    if((sc>=0)!==(sn>=0)){const t=sc/(sc-sn);out.push({x:cur.x+t*(nxt.x-cur.x),y:cur.y+t*(nxt.y-cur.y)});}
  }
  return out.length>=3?out:null;
}
function pcgSplitByLine(poly,a,b){
  const L=pcgClipHalf(poly,a,b),R=pcgClipHalf(poly,b,a);
  return [L,R].filter(p=>p&&pcgArea(p)>1);
}
// carve a real road corridor of width `gap` centred on the cut a->b
function pcgSplitWithGap(poly,a,b,gap){
  if(!gap)return pcgSplitByLine(poly,a,b);
  let dx=b.x-a.x,dy=b.y-a.y;const L=Math.hypot(dx,dy)||1;const nx=-dy/L*gap/2,ny=dx/L*gap/2;
  const left =pcgClipHalf(poly,{x:a.x+nx,y:a.y+ny},{x:b.x+nx,y:b.y+ny});
  const right=pcgClipHalf(poly,{x:b.x-nx,y:b.y-ny},{x:a.x-nx,y:a.y-ny});
  return [left,right].filter(p=>p&&pcgArea(p)>1);
}
// Create_Spline_Shape (ngon) + organic jitter of the corners
function pcgShape(radius,ngon,rnd){
  const p=[],N=Math.max(ngon,16),ph1=rnd()*6.28,ph2=rnd()*6.28;
  for(let i=0;i<N;i++){const a=Math.PI*2*i/N;
    const r=radius*(0.9+0.06*Math.sin(a*3+ph1)+0.05*Math.sin(a*5+ph2));
    p.push({x:Math.cos(a)*r*1.06,y:Math.sin(a)*r});}
  return pcgCcw(p);
}
// Create_Spline_line (straight arterial: 2 endpoints)
function pcgArtery(len,angle,offset){
  const dx=Math.cos(angle),dy=Math.sin(angle),cx=-dy*offset,cy=dx*offset;
  return [{x:cx-dx*len/2,y:cy-dy*len/2},{x:cx+dx*len/2,y:cy+dy*len/2}];
}
// Subdivide_Areas_withSpline: cut each area by each artery, carving a corridor of width `gap`
function pcgSubdivideBySplines(areas,splines,gap){
  let cur=areas;
  for(const s of splines){const a=s[0],b=s[s.length-1];
    const next=[];for(const poly of cur)next.push(...pcgSplitWithGap(poly,a,b,gap));cur=next;}
  return cur;
}
// Subdivide_Areas_WithRecursiveSplit: binary split along the long axis, N iterations, carving `gap`-wide roads
function pcgRecursiveSplit(poly,iters,maxOff,gap,rnd){
  if(iters<=0||pcgArea(poly)<20)return[poly];
  const bb=pcgBbox(poly),c=pcgCentroid(poly);
  const horiz=(bb.maxx-bb.minx)>=(bb.maxy-bb.miny);
  const off=(rnd()-.5)*2*maxOff;
  let a,b;
  if(horiz){const x=c.x+off*(bb.maxx-bb.minx);a={x,y:bb.miny-9};b={x,y:bb.maxy+9};}
  else{const y=c.y+off*(bb.maxy-bb.miny);a={x:bb.minx-9,y};b={x:bb.maxx+9,y};}
  const halves=pcgSplitWithGap(poly,a,b,gap);
  if(halves.length<2)return[poly];
  return halves.flatMap(h=>pcgRecursiveSplit(h,iters-1,maxOff,gap,rnd));
}
// Subdivide_Areas_withGrid: clip area against an axis-aligned grid -> blocks (tiling, touching)
function pcgSubdivideGrid(poly,gw,gl){
  const bb=pcgBbox(poly),blocks=[];
  for(let x=bb.minx;x<bb.maxx;x+=gw)for(let y=bb.miny;y<bb.maxy;y+=gl){
    let cell=poly;
    cell=pcgClipHalf(cell,{x,y:1},{x,y:0});           if(!cell)continue;
    cell=pcgClipHalf(cell,{x:x+gw,y:0},{x:x+gw,y:1});  if(!cell)continue;
    cell=pcgClipHalf(cell,{x:0,y},{x:1,y});            if(!cell)continue;
    cell=pcgClipHalf(cell,{x:1,y:y+gl},{x:0,y:y+gl});  if(!cell)continue;
    if(pcgArea(cell)>30)blocks.push(cell);
  }
  return blocks;
}
function pcgFilterBySize(areas,size,lesser){
  const sel=[],un=[];for(const p of areas){const keep=lesser?pcgArea(p)<size:pcgArea(p)>=size;(keep?sel:un).push(p);}return{sel,un};
}
function pcgFilterRandom(areas,ratio,rnd){
  const sel=[],un=[];for(const p of areas)(rnd()<ratio?sel:un).push(p);return{sel,un};
}
// Transform_Areas_Contract: offset by d metres (d>0 inward, d<0 outward); null if it collapses
function pcgContract(poly,d){
  const p=pcgCcw(poly),n=p.length,lines=[];
  for(let i=0;i<n;i++){const a=p[i],b=p[(i+1)%n];
    let ex=b.x-a.x,ey=b.y-a.y;const L=Math.hypot(ex,ey)||1;ex/=L;ey/=L;
    const nx=-ey,ny=ex;
    lines.push({px:a.x+nx*d,py:a.y+ny*d,dx:ex,dy:ey});
  }
  const out=[];
  for(let i=0;i<n;i++){const l1=lines[(i-1+n)%n],l2=lines[i];
    const den=l1.dx*l2.dy-l1.dy*l2.dx;if(Math.abs(den)<1e-6)return null;
    const t=((l2.px-l1.px)*l2.dy-(l2.py-l1.py)*l2.dx)/den;
    out.push({x:l1.px+l1.dx*t,y:l1.py+l1.dy*t});
  }
  return pcgArea(out)>4&&pcgArea2(pcgCcw(out))!==0?out:null;
}
function pcgPointInPoly(pt,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){
  const a=poly[i],b=poly[j];if(((a.y>pt.y)!==(b.y>pt.y))&&(pt.x<(b.x-a.x)*(pt.y-a.y)/(b.y-a.y)+a.x))inside=!inside;}return inside;}
function pcgScatter(poly,perM2,rnd){
  const bb=pcgBbox(poly),count=Math.max(1,Math.round(pcgArea(poly)*perM2)),pts=[];
  let tries=0;while(pts.length<count&&tries<count*8){tries++;
    const p={x:bb.minx+rnd()*(bb.maxx-bb.minx),y:bb.miny+rnd()*(bb.maxy-bb.miny)};
    if(pcgPointInPoly(p,poly))pts.push(p);}
  return pts;
}
// oriented bounding box of a footprint (aligned to its longest edge) -> a box building
function pcgOBB(poly){
  let bi=0,bl=-1;const n=poly.length;
  for(let i=0;i<n;i++){const a=poly[i],b=poly[(i+1)%n];const l=(b.x-a.x)**2+(b.y-a.y)**2;if(l>bl){bl=l;bi=i;}}
  const a=poly[bi],b=poly[(bi+1)%n];
  let ux=b.x-a.x,uy=b.y-a.y;const L=Math.hypot(ux,uy)||1;ux/=L;uy/=L;
  const vx=-uy,vy=ux;
  let minu=1e9,maxu=-1e9,minv=1e9,maxv=-1e9;
  for(const p of poly){const pu=p.x*ux+p.y*uy,pv=p.x*vx+p.y*vy;
    minu=Math.min(minu,pu);maxu=Math.max(maxu,pu);minv=Math.min(minv,pv);maxv=Math.max(maxv,pv);}
  const cu=(minu+maxu)/2,cv=(minv+maxv)/2;
  return {cx:cu*ux+cv*vx, cy:cu*uy+cv*vy, ang:Math.atan2(uy,ux), w:maxu-minu, d:maxv-minv};
}
// the 4 world-space corners of an oriented box
function pcgOBBCorners(o){
  const c=Math.cos(o.ang),s=Math.sin(o.ang),hw=o.w/2,hd=o.d/2;
  return [[hw,hd],[-hw,hd],[-hw,-hd],[hw,-hd]].map(([u,v])=>({x:o.cx+u*c-v*s, y:o.cy+u*s+v*c}));
}
// a buildable lot -> 1..N extruded box buildings (footprints from a light recursive split).
// `keep` is the lot minus the street ring: every emitted box is SHRUNK until its four
// corners lie inside `keep`, so a rendered building can never reach the walkable street
// nodes (which sit just OUTSIDE the lot) — cats never walk through a building (#64).
function pcgBuildingsForLot(lot,prof,rnd,keep){
  if(!keep) return [];
  const A=pcgArea(lot),out=[];
  const foots = A>3200 ? pcgRecursiveSplit(lot,2,0.18,prof.roadLocal*0.5,rnd) : [lot];
  for(const f of foots){
    const inner=pcgContract(f,Math.max(1.0,prof.roadLocal*0.16))||f;
    if(pcgArea(inner)<160)continue;
    let o=pcgOBB(inner);
    let fit=false;
    for(let s=0;s<7;s++){                                             // shrink toward centre until it clears the street
      if(pcgOBBCorners(o).every(c=>pcgPointInPoly(c,keep))){ fit=true; break; }
      o={cx:o.cx,cy:o.cy,ang:o.ang,w:o.w*0.82,d:o.d*0.82};
    }
    if(!fit || o.w<3 || o.d<3)continue;
    const centro=1-Math.min(1,Math.hypot(o.cx,o.cy)/prof.Rm);         // taller downtown
    const nz=pcgVnoise(o.cx/60+11,o.cy/60+11);                        // coherent height field
    const hm=6+(prof.maxH-6)*Math.max(0.12,Math.min(1,0.30+0.5*centro+0.35*nz-0.15));
    out.push({cx:o.cx, cy:o.cy, ang:o.ang, w:o.w, d:o.d, hm, tone:0.42+rnd()*0.5, roof: hm<12 && rnd()<0.7});
  }
  return out;
}

/* ---- the compiled graph: run the whole pipeline for one settlement ----
   Works in metres, then normalises every coordinate to the outline radius so the
   result drops straight into buildCity's normalised local space. */
function generatePCGTown(st){
  const prof=PCITY[st.tier]||PCITY.city;
  const rng=cityRng(st), rnd=()=>rng();
  const Rm=prof.Rm;
  // [A] organic outline
  const outline=pcgShape(Rm*0.94,16,rnd);
  // [S] arteries (0 / 1 / 2 by tier)
  const arteries=[];
  if(prof.arteries>=1) arteries.push(pcgArtery(2.2*Rm, rnd()*Math.PI, 0));
  if(prof.arteries>=2) arteries.push(pcgArtery(2.2*Rm, rnd()*Math.PI+Math.PI*2/3, Rm*0.22));
  // districts carved by arteries, then (city+) sub-split by collector roads
  let districts = arteries.length ? pcgSubdivideBySplines([outline],arteries,prof.roadArtery) : [outline.slice()];
  let sub = prof.distIter>0 ? districts.flatMap(d=>pcgRecursiveSplit(d,prof.distIter,0.2,prof.roadColl,rnd)) : districts.slice();
  // big districts -> blocks ; small leftovers -> reserved green
  let dividable=sub, green=[];
  if(prof.distLimit<1e8){ const f=pcgFilterBySize(sub,prof.distLimit,false); dividable=f.sel; green=f.un; }
  const blocks = dividable.flatMap(d=>pcgSubdivideGrid(d,prof.blockW,prof.blockL));
  // lots = each block contracted by half the local-road width (the gap reads as street)
  const lots = blocks.map(b=>pcgContract(b,prof.roadLocal/2)).filter(Boolean);
  // buildable vs plaza
  const {sel:buildable, un:plazas} = pcgFilterRandom(lots,prof.buildable,rnd);
  // street-node offset: how far OUTSIDE a lot the walkable road nodes sit. Buildings are
  // kept inside `lot` minus a slightly larger margin, so nodes never fall in a building.
  const off=Math.max(2.5, prof.roadLocal*0.45);
  // buildings ; oversized / random lots -> parks
  const buildings=[], parks=[...green];
  for(const lot of buildable){
    const A=pcgArea(lot);
    if(A>prof.parkArea){ parks.push(lot); continue; }
    if(rnd()<prof.parkPct){ parks.push(lot); continue; }
    // keep buildings just inside the lot (dense) — the node post-filter below is the hard
    // guarantee, so this margin only has to be small to stay off the street in the common case.
    const keep=pcgContract(lot, Math.max(0.5, off*0.35)) || pcgContract(lot, 0.5) || lot;
    for(const b of pcgBuildingsForLot(lot,prof,rnd,keep)) buildings.push(b);
  }
  // trees scattered through the greens (deterministic — done here, not at render time)
  const trees=[];
  for(const p of parks) for(const t of pcgScatter(p,prof.treeDens,rnd)) trees.push(t);
  // explicit local STREET GRAPH — nodes sit in the road ring just outside every lot (metres)
  let graph = buildStreetGraph(lots, prof.roadLocal, off);
  // hard guarantee (#64): a cat hops node -> ADJACENT node in a STRAIGHT LINE, so both the
  // nodes AND the edges between them must clear the buildings. Node-only filtering left ~1-9%
  // of edges clipping a house corner (cats cut through a building between waypoints), so:
  //   (a) drop any node inside a building box; (b) drop any surviving EDGE whose segment
  // crosses a building box. Both passes rewire adjacency — a walked path is NEVER in a house.
  {
    const inBox=p=>buildings.some(b=>{ const dx=p.x-b.cx,dy=p.y-b.cy,c=Math.cos(b.ang),s=Math.sin(b.ang);
      const u=dx*c+dy*s, v=-dx*s+dy*c; return Math.abs(u)<=b.w/2 && Math.abs(v)<=b.d/2; });
    // exact segment vs oriented-box overlap (Liang–Barsky slab clip in box-local space)
    const segHitsBox=(p,q,b)=>{ const c=Math.cos(b.ang),s=Math.sin(b.ang);
      const au=(p.x-b.cx)*c+(p.y-b.cy)*s, av=-(p.x-b.cx)*s+(p.y-b.cy)*c;
      const du=((q.x-b.cx)*c+(q.y-b.cy)*s)-au, dv=(-(q.x-b.cx)*s+(q.y-b.cy)*c)-av, hw=b.w/2, hd=b.d/2;
      let t0=0,t1=1;
      const clip=(pp,qq)=>{ if(Math.abs(pp)<1e-9) return qq>=0; const r=qq/pp;
        if(pp<0){ if(r>t1) return false; if(r>t0) t0=r; } else { if(r<t0) return false; if(r<t1) t1=r; } return true; };
      if(!clip(-du,au+hw)||!clip(du,hw-au)||!clip(-dv,av+hd)||!clip(dv,hd-av)) return false;
      return t0<=t1; };
    const edgeClear=(p,q)=>!buildings.some(b=>segHitsBox(p,q,b));
    const remap=new Array(graph.nodes.length).fill(-1), keep=[];
    graph.nodes.forEach((p,i)=>{ if(!inBox(p)){ remap[i]=keep.length; keep.push(i); } });      // (a)
    const nodes=keep.map(i=>graph.nodes[i]);
    const pruned=keep.map(i=>graph.adj[i].map(j=>remap[j]).filter(j=>j>=0));
    const adj=nodes.map(()=>[]);
    for(let i=0;i<nodes.length;i++) for(const j of pruned[i]){ if(j<=i) continue;              // (b)
      if(edgeClear(nodes[i],nodes[j])){ adj[i].push(j); adj[j].push(i); } }
    graph = nodes.length ? {nodes, adj} : {nodes:[{x:0,y:0}], adj:[[]]};
  }

  // ---- normalise everything to outline radius (~1.0) ----
  const N=Rm;
  const nPoly=poly=>poly.map(p=>({x:p.x/N,y:p.y/N}));
  return {
    tier:st.tier, profile:prof, Rm,
    outline:nPoly(outline),
    arteries:arteries.map(a=>({pts:nPoly(a), w:prof.roadArtery/N})),
    blocks:blocks.map(nPoly),
    lots:lots.map(nPoly),
    plazas:plazas.map(nPoly),
    parks:parks.map(nPoly),
    buildings:buildings.map(b=>({cx:b.cx/N, cy:b.cy/N, ang:b.ang, w:b.w/N, d:b.d/N, h:b.hm/N, tone:b.tone, roof:b.roof})),
    trees:trees.map(t=>({x:t.x/N,y:t.y/N})),
    streetGraph:{ nodes:graph.nodes.map(p=>({x:p.x/N,y:p.y/N})), adj:graph.adj },
  };
}

/* Build a walkable street graph from the lots. A lot is a block contracted by half
   the local-road width, so the ring just OUTSIDE a lot edge is street (never a
   building — every building box is kept inside the lot minus that ring, see
   pcgBuildingsForLot). Nodes are placed at each lot EDGE, pushed outward along the
   edge normal by `off` (long edges get intermediate nodes); perimeter edges loop
   each lot and near nodes of DIFFERENT lots are cross-linked across the shared
   street, so the graph is connected within a district and every edge lies on
   pavement. Edge midpoints (vs. expanded vertices) keep nodes at exactly `off` —
   no corner overshoot that could reach into a neighbouring lot. */
function buildStreetGraph(lots, roadLocal, off){
  const nodes=[], adj=[], owner=[];
  const link=(i,j)=>{ if(i!==j && !adj[i].includes(j)){ adj[i].push(j); adj[j].push(i); } };
  lots.forEach((lot,li)=>{
    if(lot.length<3) return;
    const p=pcgCcw(lot), n=p.length, first=nodes.length;
    for(let k=0;k<n;k++){
      const a=p[k], b=p[(k+1)%n];
      let ex=b.x-a.x, ey=b.y-a.y; const L=Math.hypot(ex,ey)||1; ex/=L; ey/=L;
      const nx=ey, ny=-ex;                                   // outward normal for CCW
      const steps=L>roadLocal*3.2?3:(L>roadLocal*1.6?2:1);   // intermediate nodes on long frontages
      for(let s=0;s<steps;s++){
        const tt=(s+0.5)/steps, mx=a.x+ex*L*tt, my=a.y+ey*L*tt;
        nodes.push({x:mx+nx*off, y:my+ny*off}); adj.push([]); owner.push(li);
      }
    }
    const cnt=nodes.length-first;
    for(let k=0;k<cnt;k++) link(first+k, first+((k+1)%cnt));   // perimeter loop
  });
  // spatial hash -> cross-lot links across the street gap
  const cell=Math.max(4, roadLocal*1.6);
  const grid=new Map();
  const gk=(x,y)=>Math.floor(x/cell)+','+Math.floor(y/cell);
  nodes.forEach((p,i)=>{ const k=gk(p.x,p.y); let a=grid.get(k); if(!a){a=[];grid.set(k,a);} a.push(i); });
  const thr=roadLocal*2.1, thr2=thr*thr;
  nodes.forEach((p,i)=>{
    const gx=Math.floor(p.x/cell), gy=Math.floor(p.y/cell);
    for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++){
      const a=grid.get((gx+dx)+','+(gy+dy)); if(!a) continue;
      for(const j of a){ if(j<=i||owner[j]===owner[i]) continue;
        const ex=nodes[j].x-p.x, ey=nodes[j].y-p.y; if(ex*ex+ey*ey<thr2) link(i,j); }
    }
  });
  if(!nodes.length){ nodes.push({x:0,y:0}); adj.push([]); }
  return {nodes, adj};
}

/* project a flat 2-D polygon (normalised town coords) onto the sphere and emit its
   triangles into a MeshAcc — the ground/road/park/plaza patches. */
function accFlatPoly(acc, poly, dirOf, R, lift, color){
  if(poly.length<3) return;
  const contour=poly.map(p=>new THREE.Vector2(p.x,p.y));
  let tris; try{ tris=THREE.ShapeUtils.triangulateShape(contour, []); }catch(_){ return; }
  const dir=poly.map(p=>dirOf(p.x,p.y));                 // unit surface normal at each vertex
  const pos=dir.map(d=>d.clone().multiplyScalar(R+lift));
  for(const t of tris) for(const idx of t){
    const v=pos[idx], nv=dir[idx];
    acc.pos.push(v.x,v.y,v.z); acc.nrm.push(nv.x,nv.y,nv.z); acc.col.push(color.r,color.g,color.b);
  }
}



/* --- geometry merging: one draw call per layer --- */
function MeshAcc(){ return {pos:[], nrm:[], col:[]}; }
const _m3=new THREE.Matrix3();
function accGeo(acc, geo, mat4, color){
  _m3.getNormalMatrix(mat4);
  const gp=geo.attributes.position, gn=geo.attributes.normal;
  const idx=geo.index? geo.index.array : null;
  const n=idx? idx.length : gp.count;
  const v=new THREE.Vector3(), nv=new THREE.Vector3();
  for(let i=0;i<n;i++){
    const k=idx? idx[i] : i;
    v.set(gp.getX(k),gp.getY(k),gp.getZ(k)).applyMatrix4(mat4);
    nv.set(gn.getX(k),gn.getY(k),gn.getZ(k)).applyMatrix3(_m3).normalize();
    acc.pos.push(v.x,v.y,v.z); acc.nrm.push(nv.x,nv.y,nv.z);
    acc.col.push(color.r,color.g,color.b);
  }
}
function accMesh(acc){
  const g=new THREE.BufferGeometry();
  g.setAttribute('position', new THREE.Float32BufferAttribute(acc.pos,3));
  g.setAttribute('normal', new THREE.Float32BufferAttribute(acc.nrm,3));
  g.setAttribute('color', new THREE.Float32BufferAttribute(acc.col,3));
  return new THREE.Mesh(g, new THREE.MeshLambertMaterial({vertexColors:true}));
}
const BOX=new THREE.BoxGeometry(1,1,1);
const SPH=new THREE.SphereGeometry(1,10,8);
const CONE=new THREE.ConeGeometry(1,1,7);
const DISK=new THREE.CircleGeometry(1, 44);

/* one flying cat head (sphere + ears + muzzle), sized in surface units; the group is
   placed and oriented per frame by stepWalkers. Shared primitives, per-head material. */
function makeCatHead(fur, weapon){
  const H=0.00100;
  const head=fur.clone().offsetHSL(0,0,0.05);
  const matH=new THREE.MeshLambertMaterial({color:head});
  const matM=new THREE.MeshLambertMaterial({color:head.clone().offsetHSL(0,-0.05,0.10)});
  const matW=new THREE.MeshLambertMaterial({color:0xE8E2D6});     // pale whiskers, so they read against the fur
  const g=new THREE.Group();
  const part=(geo,mat,px,py,pz,sx,sy,sz,rx,ry)=>{
    const m=new THREE.Mesh(geo,mat); m.position.set(px,py,pz); m.scale.set(sx,sy,sz);
    if(rx) m.rotation.x=rx; if(ry) m.rotation.y=ry; g.add(m);
  };
  part(SPH, matH,  0,      0,      0,      H*0.24,H*0.22,H*0.24);   // head — +Y up, +Z forward
  part(CONE,matH, -H*0.12, H*0.16, 0,      H*0.10,H*0.24,H*0.10);  // left ear  (enlarged, #54)
  part(CONE,matH,  H*0.12, H*0.16, 0,      H*0.10,H*0.24,H*0.10);  // right ear (enlarged, #54)
  part(SPH, matM,  0,     -H*0.02, H*0.18, H*0.08,H*0.06,H*0.08);  // muzzle
  // #54: whiskers — three thin bars per side, rooted at the muzzle cheeks and fanning outward in
  // the head's tangent plane (the plane the top-down camera sees). Symmetric: the right side uses
  // side=+1 / angle −θ, the left mirrors it with side=−1 / angle +θ.
  const WL=H*0.20, WT=H*0.012, bx=H*0.05, by=-H*0.02, bz=H*0.16;   // length, thickness, muzzle-cheek root
  for(const s of [1,-1]) for(const th of [0.30, 0, -0.30]){
    const cx=s*(bx + WL/2*Math.cos(th)), cz=bz + WL/2*Math.sin(th);
    part(BOX, matW, cx, by, cz, WL, WT, WT, 0, -s*th);            // elongated along its own axis, fanned by ry
  }
  // exactly one weapon per head — rifle for shooters, sword for meleers (skill rule at the call
  // site). The head is bodiless and, on the sphere, floats ears-up toward the top-down camera,
  // so the weapon lies in the tangent plane beside the head (offset +X) pointing +Z (the facing
  // / movement dir) — where it stays visible and inherits the head group's orientation. Sized
  // in H so it scales with the (enlarged) head.
  const AX=H*0.28;                                                 // floats just beside the head, to the right
  if(weapon==='rifle'){                                            // barrel runs along +Z (facing dir)
    const gun =new THREE.MeshLambertMaterial({color:0x2B2B30});
    const wood=new THREE.MeshLambertMaterial({color:0x6B4A2A});
    part(BOX, gun,  AX,  0,       H*0.06, H*0.05, H*0.06, H*0.30);  // receiver/body
    part(BOX, gun,  AX,  H*0.005, H*0.30, H*0.02, H*0.02, H*0.24);  // barrel
    part(BOX, wood, AX, -H*0.01, -H*0.18, H*0.05, H*0.07, H*0.12);  // stock
    part(BOX, gun,  AX, -H*0.09,  H*0.02, H*0.03, H*0.10, H*0.05);  // magazine (hangs down)
  }else{                                                           // sword: blade along +Z, guard across X
    const steel=new THREE.MeshLambertMaterial({color:0xC2C8D2});
    const gold =new THREE.MeshLambertMaterial({color:0x9A7B33});
    const wood =new THREE.MeshLambertMaterial({color:0x6B4A2A});
    part(BOX,  steel, AX, 0,  H*0.14, H*0.04, H*0.015,H*0.34);            // blade (flat faces camera)
    part(CONE, steel, AX, 0,  H*0.34, H*0.02, H*0.06, H*0.02, Math.PI/2); // tip — apex rotated to +Z
    part(BOX,  gold,  AX, 0, -H*0.05, H*0.14, H*0.03, H*0.04);            // cross-guard (spans X)
    part(BOX,  wood,  AX, 0, -H*0.14, H*0.03, H*0.03, H*0.12);            // grip
    part(SPH,  gold,  AX, 0, -H*0.22, H*0.035,H*0.035,H*0.035);           // pommel
  }
  return g;
}

/* --- assemble one town on the sphere --- */
let frameDtMs=16;
function buildCity(st, maxResidents=48){
  const town=generatePCGTown(st);           // #64 — PCG city generator, all tiers
  const prof=town.profile;

  const up=st.dir.clone();
  const tan=new THREE.Vector3(0,1,0).cross(up).normalize();
  const bit=up.clone().cross(tan).normalize();
  // Sit the town ON the globe surface. The globe is an analytic ray-cast of a SMOOTH
  // r=1 sphere (render.js) and the camera focuses on that surface at radius 1.0 — elevation
  // is colour-only, never geometric height. The town base must sit at R=1.0 exactly: at
  // street-level zoom the whole view spans ~0.01–0.05 radii, so even the 0.005 markers ride
  // (MARK_R) reads as a visible float for the big city geometry. R>1 floated it (#88 tried
  // 1.005 — still visibly off the ground); 1.0 pins it flush to the surface.
  const R=1.0;
  const S1=prof.radius;                       // per-tier surface radius (footprint size on the sphere)

  const dirOf=(x,y)=>up.clone().add(tan.clone().multiplyScalar(x*S1))
                                .add(bit.clone().multiplyScalar(y*S1)).normalize();
  const M=new THREE.Matrix4();
  const orient=(x,y,ang,lift)=>{
    const n=dirOf(x,y);
    const p=n.clone().multiplyScalar(R+lift);
    const t2=tan.clone().multiplyScalar(Math.cos(ang)).add(bit.clone().multiplyScalar(Math.sin(ang)));
    const b2=n.clone().cross(t2).normalize();
    const t3=b2.clone().cross(n).normalize();
    M.makeBasis(t3, n, b2); M.setPosition(p);
    return M.clone();
  };
  const scale=(m,x,y,z)=>m.multiply(new THREE.Matrix4().makeScale(x,y,z));

  const group=new THREE.Group();
  const col=new THREE.Color();

  // ---- 1. ground layers (roads show through the gaps) : one merged mesh ----
  const gAcc=MeshAcc();
  // pavement disk under the whole town — the road base
  {
    const n=up.clone(), p=n.clone().multiplyScalar(R+0.00002);
    const t2=tan.clone(), b2=n.clone().cross(t2).normalize(), t3=b2.clone().cross(n).normalize();
    const m=new THREE.Matrix4().makeBasis(t3, n, b2);
    m.setPosition(p);
    m.multiply(new THREE.Matrix4().makeRotationX(-Math.PI/2));
    m.multiply(new THREE.Matrix4().makeScale(S1*1.03, S1*1.03, 1));
    col.set(0x37342E); accGeo(gAcc, DISK, m, col);
  }
  // arteries — widest paved ribbons (megalopolis/city only)
  col.set(0x2C2A25);
  for(const a of town.arteries){
    for(let i=0;i<a.pts.length-1;i++){
      const p0=a.pts[i], p1=a.pts[i+1];
      let dx=p1.x-p0.x, dy=p1.y-p0.y; const L=Math.hypot(dx,dy)||1; const nx=-dy/L*a.w/2, ny=dx/L*a.w/2;
      accFlatPoly(gAcc,[{x:p0.x+nx,y:p0.y+ny},{x:p1.x+nx,y:p1.y+ny},{x:p1.x-nx,y:p1.y-ny},{x:p0.x-nx,y:p0.y-ny}],dirOf,R,0.00004,col);
    }
  }
  // blocks (sidewalk grey) -> lots (ground tan): the grey ring left between reads as the local street
  col.setHSL(0.09,0.06,0.34); for(const b of town.blocks) accFlatPoly(gAcc,b,dirOf,R,0.00006,col);
  col.setHSL(0.09,0.10,0.46); for(const l of town.lots)   accFlatPoly(gAcc,l,dirOf,R,0.00009,col);
  col.setHSL(0.11,0.30,0.42); for(const p of town.plazas) accFlatPoly(gAcc,p,dirOf,R,0.00010,col);
  col.setHSL(0.30,0.34,0.30); for(const p of town.parks)  accFlatPoly(gAcc,p,dirOf,R,0.00011,col);
  group.add(accMesh(gAcc));

  // ---- 2. buildings : extruded boxes, one merged mesh ----
  //    In-settlement enterprises (forge/workshop/armory...) are assigned to lots:
  //    the largest buildings become their premises (tinted + a rooftop beacon).
  const inside=S.ents.filter(e=>e.settlementId===st.id && ENT[e.kind] && ENT[e.kind].inside);
  const order=town.buildings.map((b,i)=>i).sort((p,q)=>(town.buildings[q].w*town.buildings[q].d)-(town.buildings[p].w*town.buildings[p].d));
  const entOf={};
  inside.forEach((e,i)=>{ if(i<order.length){ const bi=order[i]; entOf[bi]=e; e._cityDir=dirOf(town.buildings[bi].cx, town.buildings[bi].cy); } });

  const bAcc=MeshAcc();
  town.buildings.forEach((b,i)=>{
    const hs=b.h*S1*prof.heightExag, meters=b.h*prof.Rm;
    const m=orient(b.cx, b.cy, b.ang, hs/2 + 0.00012);
    scale(m, b.w*S1, hs, b.d*S1);
    if(entOf[i]) col.setHSL(0.10, 0.52, 0.44);                          // enterprise premises
    else col.setHSL(0.075+pcgVnoise(b.cx*7+3,b.cy*7+3)*0.05, 0.14+0.06*(1-Math.min(1,Math.hypot(b.cx,b.cy))), 0.24+b.tone*0.30);
    accGeo(bAcc, BOX, m, col);
    if(entOf[i]){                                                        // rooftop beacon marks the premises
      const km=orient(b.cx, b.cy, b.ang, hs+0.00012+0.00030);
      scale(km, b.w*S1*0.34, 0.00060, b.d*S1*0.34);
      col.setHSL(0.11,0.75,0.60); accGeo(bAcc, BOX, km, col);
    } else if(b.roof){
      const rm=orient(b.cx, b.cy, b.ang, hs+0.00012+0.00022);
      scale(rm, b.w*S1*0.82, 0.00044, b.d*S1*0.82);
      col.setHSL(0.035, 0.32, 0.20+b.tone*0.08); accGeo(bAcc, BOX, rm, col);
    } else if(meters>=24){                                              // a plinth line so towers don't read as bars
      const cm=orient(b.cx, b.cy, b.ang, hs+0.00012);
      scale(cm, b.w*S1*1.04, 0.00016, b.d*S1*1.04);
      col.setHSL(0.07, 0.08, 0.20); accGeo(bAcc, BOX, cm, col);
    }
  });
  if(bAcc.pos.length) group.add(accMesh(bAcc));

  // ---- 3. trees on the greens ----
  const pAcc=MeshAcc();
  for(const t of town.trees){
    if(Math.hypot(t.x,t.y)>1.02) continue;
    const m=orient(t.x, t.y, 0, 0.0016); scale(m, 0.0015, 0.0032, 0.0015);
    col.set(0x3f7d4f); accGeo(pAcc, CONE, m, col);
  }
  if(pAcc.pos.length) group.add(accMesh(pAcc));

  // ---- 4. residents: flying cat heads that WALK the generated street graph ----
  //    Each waypoint is a graph node in the road ring around a lot, and each hop is
  //    a graph edge — so a head is always on a street and never crosses a building.
  const walkers=[];
  const G=town.streetGraph, NODES=G.nodes;
  const nextWaypoint=(w)=>{
    const n=NODES.length; if(!n) return {x:0,y:0};
    const a=(w && w.node!=null) ? G.adj[w.node] : null;
    // hop to an ADJACENT node (a building-free graph edge). If the current node is isolated
    // (its edges were pruned as building-crossing), IDLE on it — never teleport to a random
    // far node, which would draw a straight line across town THROUGH buildings (#64).
    let ni = (a && a.length) ? a[(Math.random()*a.length)|0]
           : (w && w.node!=null ? w.node : (Math.random()*n)|0);
    if(w) w.node=ni;
    const p=NODES[ni]; return {x:p.x, y:p.y};
  };
  const realResidents=S.chars.filter(c=>c.homeId===st.id && c.alive);
  const footprint=town.lots.length;
  const wanted=Math.min(110, Math.round(footprint*1.7));
  const total=Math.min(maxResidents, Math.max(realResidents.length, wanted));
  const spawnWalker=(seed, char)=>{
    const w={ id: char? char.id : null, mesh:null, x:0, y:0, node:null, tgt:null,
              face:(seed%360)/360*Math.PI*2, spd:0.09+((seed%5)/5)*0.07, phase:(seed%12)/12*6.283, dir:null };
    const start = NODES.length ? NODES[seed%NODES.length] : {x:0,y:0};
    w.x=start.x; w.y=start.y; w.node=NODES.length? (seed%NODES.length) : null;
    w.tgt=nextWaypoint(w); w.dir=dirOf(w.x,w.y);
    const isLeader=char && !!char.ledOrgId, isPlayer=char && char.id===S.playerCharId;
    const fur = isPlayer? new THREE.Color(0xC89B3C)
              : isLeader? new THREE.Color(0xEADCB6)
              : new THREE.Color().setHSL(0.07+((seed%9)/9)*0.06, 0.18+((seed%3)*0.10), 0.42+((seed%5)/5)*0.28);
    const weapon = char ? (char.skills.shooting > char.skills.melee ? 'rifle' : 'sword')
                        : ((seed%2) ? 'rifle' : 'sword');
    const head=makeCatHead(fur, weapon);
    head.matrixAutoUpdate=false;
    group.add(head); w.mesh=head; walkers.push(w);
  };
  for(let k=0;k<total;k++){
    if(k<realResidents.length) spawnWalker(realResidents[k].id, realResidents[k]);
    else spawnWalker((st.id*131+k*9277+7)>>>0, null);
  }

  root.add(group);
  return {group, walkers, st, orient, dirOf, nextWaypoint, R, town};   // town exposed for tests (#64) / #50: R for head-aligned picks
}

/* advance one town's walking cat heads along the streets by one frame's worth of time */
function stepWalkers(c, dtMs){
  if(!c.walkers || !c.walkers.length) return;
  const H=0.00100, sp = S.paused? 0 : S.speed;
  for(const w of c.walkers){
    if(sp>0){
      const dx=w.tgt.x-w.x, dy=w.tgt.y-w.y, d=Math.hypot(dx,dy);
      if(d<0.006){ w.x=w.tgt.x; w.y=w.tgt.y; w.tgt=c.nextWaypoint(w); }   // SNAP exactly onto the node, then hop to an adjacent one — the walked path stays ON the (building-free) graph edges and never cuts a corner into a house (#64)
      else{
        const mv=Math.min(d, w.spd*dtMs*0.001*sp);
        w.x+=dx/d*mv; w.y+=dy/d*mv; w.face=Math.atan2(dy,dx);
      }
      w.phase+=dtMs*0.004*sp;
    }
    const bob=Math.abs(Math.sin(w.phase))*(H*0.15);
    const lift=H*0.30 + bob;
    w.mesh.matrix.copy(c.orient(w.x, w.y, w.face, lift));
    w.mesh.matrixWorldNeedsUpdate=true;
    w.dir=c.dirOf(w.x, w.y);
    w.r=(c.R!=null?c.R:1)+lift;
  }
}



// --- cross-module setters (owning module mutates its own binding) ---
export function setFrameDt(ms){ frameDtMs=ms; }

export {
  BOX, CONE, DISK, MeshAcc, PCITY, SPH, _m3, accFlatPoly, accGeo, accMesh, buildCity, buildStreetGraph,
  cityRng, frameDtMs, generatePCGTown, makeCatHead, pcgArea, pcgArea2, pcgArtery, pcgBbox, pcgBuildingsForLot, pcgCcw, pcgCentroid, pcgClipHalf,
  pcgContract, pcgFilterBySize, pcgFilterRandom, pcgHash2, pcgOBB, pcgOBBCorners, pcgPointInPoly, pcgRecursiveSplit, pcgScatter, pcgShape, pcgSplitByLine, pcgSplitWithGap,
  pcgSubdivideBySplines, pcgSubdivideGrid, pcgVnoise, stepWalkers,
};
